### ISSUE TITLE
Schedule Details界面文字显示不全问题

### ISSUE THREAD

**Issue by SaltyKitkat** [UNIDY2002/THUInfo#150]
![S10512-17394199.jpg](https://user-images.githubusercontent.com/56984513/117954077-40700600-b349-11eb-997b-b7c62261e658.jpg)
时间部分文字显示不全…

今天突然想看一眼几点下课，然后就发现了这个问题😂

**Comment by UNIDY2002** [comment]
thx~ @Ashitemaru 来修

**Comment by Ashitemaru** [comment]
应该是英语太长爆了
这星期和教学评估一块修了吧

**Comment by SaltyKitkat** [comment]
> 应该是英语太长爆了
是的呢，好多软件切到英语ui经常会有这个问题😂

**Comment by UNIDY2002** [comment]
Fixed in cdcf57b4
