### ISSUE TITLE
建议添加订水功能

### ISSUE THREAD

**Issue by THUzxj** [UNIDY2002/THUInfo#153]
感谢开发者的优秀工作！
给紫荆宿舍提供服务的清紫源泉公司的订水操作过于复杂，包括进入微信公众号，输入id，检查表单等。我对网站进行了抓包发现api逻辑很简单，只有2个，同时没有用户认证。
我觉得在app中添加一个订水功能可能会给大家带来方便，所以请予以考虑。我也可以提供帮助甚至直接添加代码。
再次感谢开发者。

**Comment by UNIDY2002** [comment]
听起来是个不错的想法，非常感谢！
我还没仔细看过订水的流程，既然您已经进行过抓包分析，我觉得直接由您来贡献代码是最好的。
我目前不太确定的地方在于，它是从微信公众号进入的，我对这块不是很了解，不清楚是否有微信那边的认证环节。
如果您打算直接添加代码，但不想本地跑起完整的 APP，或者不想写界面的话，只贡献网络交互的核心代码就行。对于该项目框架有任何疑问也欢迎随时提出。
再次感谢您的参与~

**Comment by THUzxj** [comment]
据我了解他们的网站没有使用微信认证，尝试过简单的表单提交是可以成功订水的。
近期我去了解一下你们的项目，看看怎么贡献比较合适，谢谢~

**Comment by Konano** [comment]
> 据我了解他们的网站没有使用微信认证，尝试过简单的表单提交是可以成功订水的。
> 近期我去了解一下你们的项目，看看怎么贡献比较合适，谢谢~

我复现过订水的整个过程，发现其后台无论订水成功与否都会返回「成功」，但在经过订水后台系统的核实后发现并没有成功预定上……

**Comment by THUzxj** [comment]
> > 据我了解他们的网站没有使用微信认证，尝试过简单的表单提交是可以成功订水的。
> > 近期我去了解一下你们的项目，看看怎么贡献比较合适，谢谢~
> 
> 我复现过订水的整个过程，发现其后台无论订水成功与否都会返回「成功」，但在经过订水后台系统的核实后发现并没有成功预定上……
，
您是指自己用发包工具测试，还是用我提交的代码测试？我最近一直在用手机上的发包工具ApiClient订水，是可以成功的。但很抱歉没有仔细测试代码，只试过一次印象中是成功了，但是不记得还有没有干扰，最近我有机会再试一下。

**Comment by THUzxj** [comment]
紫二又试了两次，是可以的，但不知道其他的楼怎么样，也不知道是不是一个供应商...

**Comment by UNIDY2002** [comment]
我今天会把这个功能集成到 APP 里，再次感谢您的贡献！
我之前没有用过这家的订水功能，所以有一个小疑问，就是这个档案号，最一开始是怎么得到的呀，还是允许用户自己创建？

**Comment by Konano** [comment]
> 我今天会把这个功能集成到 APP 里，再次感谢您的贡献！
> 我之前没有用过这家的订水功能，所以有一个小疑问，就是这个档案号，最一开始是怎么得到的呀，还是允许用户自己创建？

档案号是定水公司他们给的，不是自己创建的

**Comment by THUzxj** [comment]
hello，
最近用app试了两次，比官方好用多了，谢谢你们🤩。
不过还有个建议是，可否把档案号，订水类型存储在app里，因为每个人使用的信息比较固定，减少输入操作也可以自己配置语音助手的自动执行操作。

**Comment by UNIDY2002** [comment]
> hello， 最近用app试了两次，比官方好用多了，谢谢你们star_struck。 不过还有个建议是，可否把档案号，订水类型存储在app里，因为每个人使用的信息比较固定，减少输入操作也可以自己配置语音助手的自动执行操作。

好呀，也感谢你的支持～
