### ISSUE TITLE
请求添加电表余额查询功能

### ISSUE THREAD

**Issue by Konano** [UNIDY2002/THUInfo#164]
本来想尝试写脚本的，发现家园网的登陆操作巨复杂……
发现 THUInfo 已经内置了充电的实验性功能，同时还能查询充电记录，猜测应该是逆向完了登陆行为，故请求将电表余额查询加到 App 内

**Comment by Konano** [comment]
以及可以的话想请教下家园网的登陆部分怎么用脚本模拟 Orz

**Comment by UNIDY2002** [comment]
**关于电表余额查询**

之前没有做这个功能的原因是，我自己在家园网上看到的页面一直是这样的：
![image](https://user-images.githubusercontent.com/41641284/127501587-243f430c-8e79-40e8-93ff-2c426bb737dc.png)
（虽然我确实住在紫荆学生公寓二号楼。）

不过或许其他同学能够正常查到电表余额，而且既然有这个需求，我可以有空的时候把这个功能先写出来，有什么问题再具体调试。

---

**关于家园网登录**

> 如果要阅读网络部分的具体代码实现，可移步 https://github.com/thu-info-community/thu-info-lib 。

首先说明一件事，家园网有网页版和微信版，两者能够提供的功能不完全重合。在 THUInfo 里，电费相关的部分用的网页版（原因是方便接支付宝），卫生成绩相关的部分用的微信版（原因是网页版根本就不提供这个功能）。接下来的叙述里，我暂时只提网页版的事。

网页版登录部分的代码见 https://github.com/thu-info-community/thu-info-lib/blob/main/src/lib/core.ts#L197-L225 ，只要 POST 一份表单就可以了，登录用户名是学号，密码就是家园网密码，所以流程本身并不长。如果想要自己捣鼓一通登录的流程，**有几个坑必须要强调**：
- 如果你的登录密码中存在非法字符，必须先将其剔除。例如，如果你的密码为`abc@123`，那么提交表单时，密码字段的值须为`abc123`。我曾经试出过一些合法字符，可以看代码中的`validChars`。
- 我并没有严格模拟网页表单的真实内容。事实上，你可以看到我甚至直接用`dummyContent`填充了部分字段。也就是说，虽然这份代码暂时貌似能用，但理论上是有缺陷的。

查询充值记录的代码见 https://github.com/thu-info-community/thu-info-lib/blob/main/src/lib/dorm.ts#L68-L79 ，其实很简单，只要 GET 一下`ELE_PAY_RECORD_URL`的网页内容，提取一下表格数据就行了。

真正麻烦的是在充值部分。 **如果你没有做好充足的心理准备，不建议你轻易尝试复现。** 它的流程很繁琐，且使用的汉字编码完全不统一。目前存在一个已知漏洞：
- 当用户的家园网账号昵称含有非 ASCII 字符时，由于汉字编码问题，用户会遭遇**钱已经打给学校但自己的账号并没有得到充值的**问题。该漏洞尚未得到修复。

---

总之，家园网确实是个不简单的事。 ~~（我估计这个家园网的岁数至少比我大……）~~ 祝好，如有问题我们继续交流~

---

附：`http://myhome.tsinghua.edu.cn/` 经 WebVPN 转化为 `https://webvpn.tsinghua.edu.cn/http/77726476706e69737468656265737421fdee49932a3526446d0187ab9040227bca90a6e14cc9/`。在校园网环境下，你可以先用`http://myhome.tsinghua.edu.cn/`进行调试，以暂且回避 WebVPN 的登录流程，降低工作量。

**Comment by Konano** [comment]
感谢！帮了大忙了！（紫荆学生公寓二号楼好像就是没办法查询余额，南区宿舍楼就可以，我也表示很疑惑）

**Comment by ZenithalHourlyRate** [comment]
FYI, https://github.com/ZenithalHourlyRate/thuservices/blob/master/aux/TsinghuaElectricityBillChecker.py

**Comment by UNIDY2002** [comment]
thu-info-lib 中已添加这部分的代码（ https://github.com/thu-info-community/thu-info-lib/commit/b353f78bedfb1f3423d7ccd2f7f62044c03c2bbb ），之后很快同步到 THUInfo 中。

感谢 @Konano @ZenithalHourlyRate
