### ISSUE TITLE
首页-生活部分可考虑集成“洗衣机查询”功能

### ISSUE THREAD

**Issue by Hobart-Lin** [UNIDY2002/THUInfo#173]
洗衣机/洗鞋机/烘干机是同学们平时生活中常用的设备，但时不时去瞅一瞅它们是否空闲是很麻烦的。THUInfo如果能查询这些机器状态的话会带来便利。
已有同学制作了可以查询洗衣机状态的[网站](https://washer.sdevs.top/)，信息非常全面，也许THUInfo可以联系使用。

下面是一个供参考的补充功能：
提供预约功能，可预约指定机器。预约后，当该机器进入空闲状态时提醒用户。

**Comment by UNIDY2002** [comment]
很实用的建议，可行性看上去也不错，我接下来一段时间有空的时候做一下～
