### ISSUE TITLE
本地编译报错

### ISSUE THREAD

**Issue by t4rf9** [UNIDY2002/THUInfo#217]
我试图在m1 macbook pro上使用`yarn android`为android编译，但是报错THUInfo/android/build.gradle第7行的../package.json找不到，然而文件系统中它确实存在于THUInfo下。
请问这是否是android sdk或者java之类的东西没配好还是别的什么问题？
我能够完成react-native的[环境搭建指南](https://reactnative.dev/docs/environment-setup)，实现其示例项目的编译。
以下是在THUInfo目录下`yarn android`的输出，其中绝对路径都已改为THUInfo开头的相对路径。
```
yarn run v1.22.18
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1618 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

FAILURE: Build failed with an exception.

* Where:
Build file 'THUInfo/android/build.gradle' line: 7

* What went wrong:
A problem occurred evaluating root project 'thu_info'.
> ../package.json (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file 'THUInfo/android/build.gradle' line: 7

* What went wrong:
A problem occurred evaluating root project 'thu_info'.
> ../package.json (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at makeError (THUInfo/node_modules/execa/index.js:174:9)
    at THUInfo/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (THUInfo/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (THUInfo/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by UNIDY2002** [comment]
请问您是在哪个目录下执行 yarn android 的呀，直接在 THUInfo 目录下执行即可

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Zexi ***@***.***>
Sent: Sunday, March 20, 2022 10:25:27 AM
To: UNIDY2002/THUInfo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [UNIDY2002/THUInfo] 本地编译报错 (Issue #217)


我试图在m1 macbook pro上使用yarn android为android编译，但是报错THUInfo/android/build.gradle第7行的../package.json找不到，然而文件系统中它确实存在于THUInfo下。
请问这是否是android sdk或者java之类的东西没配好还是别的什么问题？

yarn run v1.22.18

$ react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.

Jetifier found 1618 file(s) to forward-jetify. Using 8 workers...

info JS server already running.

info Installing the app...



FAILURE: Build failed with an exception.



* Where:

Build file 'THUInfo/android/build.gradle' line: 7



* What went wrong:

A problem occurred evaluating root project 'thu_info'.

> ../package.json (No such file or directory)



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 2s



error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.

Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081



FAILURE: Build failed with an exception.



* Where:

Build file 'THUInfo/android/build.gradle' line: 7



* What went wrong:

A problem occurred evaluating root project 'thu_info'.

> ../package.json (No such file or directory)



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 2s



    at makeError (THUInfo/node_modules/execa/index.js:174:9)

    at THUInfo/node_modules/execa/index.js:278:16

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    at async runOnAllDevices ***@***.***/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)

    at async Command.handleAction ***@***.***/cli/build/index.js:192:9)

info Run CLI with --verbose flag for more details.

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.



―

**Comment by UNIDY2002** [comment]
build.gradle 中的 getNpmVersion 函数是我自己加的，用于自动从 package.json 中读取版本号的函数，您可以先把这个函数的返回值手动改为 package.json 中对应字段的值试试看，不知道会不会有效果。

**Comment by t4rf9** [comment]
我确实是在THUInfo下执行的，不过我不很了解gradle，之后按您在issue里回复的直接改改看发自我的手机-------- 原始邮件 --------发件人： Xun Sun ***@***.***>日期： 2022年3月20日周日 12:41收件人： UNIDY2002/THUInfo ***@***.***>抄送： Zexi ***@***.***>, Author ***@***.***>主    题： Re: [UNIDY2002/THUInfo] 本地编译报错 (Issue #217)

请问您是在哪个目录下执行 yarn android 的呀，直接在 THUInfo 目录下执行即可







Get Outlook for Android<https://aka.ms/AAb9ysg>



________________________________



From: Zexi ***@***.***>



Sent: Sunday, March 20, 2022 10:25:27 AM



To: UNIDY2002/THUInfo ***@***.***>



Cc: Subscribed ***@***.***>



Subject: [UNIDY2002/THUInfo] 本地编译报错 (Issue #217)











我试图在m1 macbook pro上使用yarn android为android编译，但是报错THUInfo/android/build.gradle第7行的../package.json找不到，然而文件系统中它确实存在于THUInfo下。



请问这是否是android sdk或者java之类的东西没配好还是别的什么问题？







yarn run v1.22.18







$ react-native run-android







info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.







Jetifier found 1618 file(s) to forward-jetify. Using 8 workers...







info JS server already running.







info Installing the app...















FAILURE: Build failed with an exception.















* Where:







Build file 'THUInfo/android/build.gradle' line: 7















* What went wrong:







A problem occurred evaluating root project 'thu_info'.







> ../package.json (No such file or directory)















* Try:







Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.















* Get more help at https://help.gradle.org















BUILD FAILED in 2s















error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.







Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081















FAILURE: Build failed with an exception.















* Where:







Build file 'THUInfo/android/build.gradle' line: 7















* What went wrong:







A problem occurred evaluating root project 'thu_info'.







> ../package.json (No such file or directory)















* Try:







Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.















* Get more help at https://help.gradle.org















BUILD FAILED in 2s















    at makeError (THUInfo/node_modules/execa/index.js:174:9)







    at THUInfo/node_modules/execa/index.js:278:16







    at processTicksAndRejections (node:internal/process/task_queues:96:5)







    at async runOnAllDevices ***@***.***/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)







    at async Command.handleAction ***@***.***/cli/build/index.js:192:9)







info Run CLI with --verbose flag for more details.







error Command failed with exit code 1.







info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.















―

**Comment by t4rf9** [comment]
通过将相对路径改为绝对路径，该问题得以解决
