### ISSUE TITLE
Unsupported class file major version 60

### ISSUE THREAD

**Issue by wihn2021** [UNIDY2002/THUInfo#237]
> yarn run v1.22.18
> warning ..\..\package.json: No license field
> $ react-native run-android
> info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
> Jetifier found 1700 file(s) to forward-jetify. Using 12 workers...
> info Starting JS server...
> '"adb"' 

> �����ڲ����ⲿ���Ҳ���ǿ����еĳ���

> �������ļ�
> info Launching emulator...
> error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
> warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
> info Installing the app...
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Settings file 'C:\Users\86198\WebstormProjects\THUInfo\android\settings.gradle'
> 
> * What went wrong:
> Could not compile settings file 'C:\Users\86198\WebstormProjects\THUInfo\android\settings.gradle'.
> > startup failed:
>   General error during semantic analysis: Unsupported class file major version 60
> 
>   java.lang.IllegalArgumentException: Unsupported class file major version 60
>         at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
>         at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
>         at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
>         ...
>         ...
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
>         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
>         at java.base/java.lang.Thread.run(Thread.java:831)
> 
>   1 error
> 
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s
> 
>     at makeError (C:\Users\86198\WebstormProjects\THUInfo\node_modules\execa\index.js:174:9)
>     at C:\Users\86198\WebstormProjects\THUInfo\node_modules\execa\index.js:278:16
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async runOnAllDevices (C:\Users\86198\WebstormProjects\THUInfo\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)     
>     at async Command.handleAction (C:\Users\86198\WebstormProjects\THUInfo\node_modules\@react-native-community\cli\build\index.js:192:9)
> info Run CLI with --verbose flag for more details.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

This is the output and I can't find where was wrong. Below is my environments. Nodejs is the latest LTS version, which meets the needs.
![image](https://user-images.githubusercontent.com/88038740/167828603-46494a2a-5d08-49d5-b69c-a1d0f27d76fd.png)
![image](https://user-images.githubusercontent.com/88038740/167828658-6362467d-a0af-4ab5-86f8-1503281e2fc7.png)
![image](https://user-images.githubusercontent.com/88038740/167828682-8077dda2-c4a9-4f0f-91bd-b2af5ad6a86a.png)

**Comment by UNIDY2002** [comment]
Hi! Sorry for the late reply. I notice that the issue is closed, so is the problem solved?

**Comment by UNIDY2002** [comment]
It seems that the java toolchain in our project is out of date (as for me, I am still using jdk 11😂). I think it is time to make some upgrade.

**Comment by wihn2021** [comment]
> 

Thank you for your reply! Later I found some errors in my local configuration and fixed them. 🤣 
However, as I compile the master branch with debug settings, the application seems have fewer icons/abilities in the main menu than the release apk, does it go wrong?

**Comment by UNIDY2002** [comment]
The behavior is expected. Since we are working on a new UI design, some functions are hidden during development stage.

You can configure it by changing the value of `needToShowFunctionNames` in `src/ui/home/home.tsx`. Good luck!
