### ISSUE TITLE
Semester not changed

### ISSUE THREAD

**Issue by HongYurui** [UNIDY2002/THUInfo#272]
The current semester did not switch to 2022 fall, instead showing a non-existing 12th week of the summer semester. The schedule is left blank. Force logout and re-login did not solve the problem.

![IMG_20220913_084309.jpg](https://user-images.githubusercontent.com/83064277/189783085-a40eb872-5d65-42b2-b432-4ce034b1af22.jpg)

**Comment by UNIDY2002** [comment]
Thanks for your feedback! Due to an error in https://info2021.tsinghua.edu.cn, school calendar cannot be properly fetched and users of this APP might encounter problems. We have reported the error of info2021 and we hope that this issue will be solved soon.

**Comment by UNIDY2002** [comment]
Solved.
