### ISSUE TITLE
课程表日期有误

### ISSUE THREAD

**Issue by CalaW** [UNIDY2002/THUInfo#273]
今天是9.14日星期三，但课程表中显示的是9.15日。
看起来秋季学期所有的日期都向后错了一天。

![1491663126411_ pic](https://user-images.githubusercontent.com/41041381/190053587-b068e8c0-8ca8-4e5c-ab20-360f58884528.jpg)

**Comment by UNIDY2002** [comment]
感谢反馈，会尽快修复

**Comment by UNIDY2002** [comment]
已修复，稍后会发布更新。
