### ISSUE TITLE
卡挂失图标不够明显

### ISSUE THREAD

**Issue by 84634E1A607A** [UNIDY2002/THUInfo#281]
**Is your feature request related to a problem? Please describe.**

我是在瞎点的时候点进去了才发现。

**Describe the solution you'd like**

换成文字是我觉得最好的方案。

**Describe alternatives you've considered**

把图标换成红的。

**Additional context**

**Comment by UNIDY2002** [comment]
采用这一图标设计的考虑是，为未来增加其它校园卡相关功能提供扩展性，也就是说，这个页面未来可能不仅仅有挂失功能。
目前还没发现有什么新功能，不过一直有消息称，学校会重新设计一套 IC 卡系统，那时候我们也许就能解锁更多能力了。

**Comment by 84634E1A607A** [comment]
> 直有消息称，学校会重新设计一套 IC 卡系统

现在的IC卡系统还不够复杂吗 (

**Comment by UNIDY2002** [comment]
> > 直有消息称，学校会重新设计一套 IC 卡系统
> 
> 现在的IC卡系统还不够复杂吗 (

我印象中，号称能直接在支付宝上充钱。希望能向北大的 IC 卡系统看齐吧……
