### ISSUE TITLE
教学评估返回网络错误：不在开放时间

### ISSUE THREAD

**Issue by 84634E1A607A** [UNIDY2002/THUInfo#283]
**Expected behavior**
A clear and concise description of what you expected to happen

应该特判返回不在开放时间时不输出网络错误提示 （2版本好像是对的）

**Screenshots**

**Version**
Enter the version of your application.

master

**Device**
Enter your device information.

**Additional context**

**Comment by UNIDY2002** [comment]
暂无法复现
