### ISSUE TITLE
减小页面与通知栏间的间隔

### ISSUE THREAD

**Issue by 84634E1A607A** [UNIDY2002/THUInfo#300]
尤其是课程计划页面的Week 6 跟通知栏隔了相当长的一段距离, 挺怪的.

**Comment by UNIDY2002** [comment]
你的测试环境是模拟器还是真机？有无手机型号信息可供参考？

**Comment by 84634E1A607A** [comment]
模拟器+真机.

真机: Huawei Mate 9 screen resolution 1080x1920 480dpi
![t](https://user-images.githubusercontent.com/60734649/196195099-fd2baf56-a10c-4f8b-b1eb-6695dfc9a816.png)

408dpi (这个好一点)
![t](https://user-images.githubusercontent.com/60734649/196195829-bbd28778-5799-41b6-bf47-64569353e573.png)

模拟器在另一套系统上所以不便放图

**Comment by 84634E1A607A** [comment]
模拟器， 
![image](https://user-images.githubusercontent.com/60734649/196200517-fb7b9429-5569-467b-93b0-429c68878c76.png)

```bash
➜  ~ adb shell wm size
Physical size: 1080x2160
➜  ~ adb shell wm density
Physical density: 440
```

**Comment by UNIDY2002** [comment]
另外我注意到你的标题栏和页面背景色不同，不过这可能和手机厂商有关了（我模拟器上也是和你一样的表现）
![Screenshot_2022-10-17-22-18-49-644_com.unidy2002.thuinfo.jpg](https://user-images.githubusercontent.com/41641284/196201732-5d8beafa-3227-4877-804f-0be11550f191.jpg)
