### ISSUE TITLE
电费充值失败

### ISSUE THREAD

**Issue by SaltyKitkat** [UNIDY2002/THUInfo#35]
于2020年9月25日下午充值电费，未到账
与学校核实，校方发现一订单中充值用户名称为乱码，订单信息中无宿舍号

**Comment by UNIDY2002** [comment]
收到，为该APP带来的经济损失表示歉意，正在排查。
顺便问一下你使用的APP是哪一个版本，是最新版嘛，谢谢！
（以及以后遇到问题不如先向我们反馈，我们肯定会积极想办法解决问题的，毕竟我们的APP也想活命qwq）

**Comment by SaltyKitkat** [comment]
> Current version: v2.0.0-rc2

以及之前同学在另一个账户上试着充了两元是充上了的，可能和用户名或id之类的东西有关?

**Comment by UNIDY2002** [comment]
谢谢反馈！你的myhome.tsinghua.edu.cn用户名中有汉字等非ASCII符号么

**Comment by SaltyKitkat** [comment]
以及想要找回损失只能去找学校啊，毕竟钱已经打过去了QAQ

**Comment by UNIDY2002** [comment]
嗯嗯没事qwq，我也很感谢，毕竟你提到用户名是乱码这一点估计提供了很有效的信息

**Comment by UNIDY2002** [comment]
用户名应该能在进入myhome.tsinghua.edu.cn后的“完善个人信息”部分找到

**Comment by SaltyKitkat** [comment]
好像的确是因为名称带中文
之前全ASCII的用户名是充值成功了的

**Comment by SaltyKitkat** [comment]
学校调查的来加微信了QAQ
我把github 链接给他发过去成不？

**Comment by UNIDY2002** [comment]
呜呜我觉得不太可qwq

**Comment by UNIDY2002** [comment]
我想一想

**Comment by UNIDY2002** [comment]
是询问你怎么操作的之类的原因么

**Comment by SaltyKitkat** [comment]
他应该是要看看软件吧QAQ

**Comment by UNIDY2002** [comment]
唔，那边现在知道些什么，是知道这个软件的存在嘛

**Comment by SaltyKitkat** [comment]
是的QAQ

**Comment by SaltyKitkat** [comment]
抱歉给你添麻烦了

**Comment by UNIDY2002** [comment]
行吧，既然知道了那也行

**Comment by UNIDY2002** [comment]
对了，我今天晚些时候会尝试修复一下这个漏洞，到时候通知你帮忙测试一下，可以嘛

**Comment by SaltyKitkat** [comment]
啊这
测试如果涉及到钱的话
学校那边可能emm...不大好吧

**Comment by UNIDY2002** [comment]
唔行，没关系，先这样好了

**Comment by SaltyKitkat** [comment]
![519C533CF73929CC563FD3116447E0DE](https://user-images.githubusercontent.com/56984513/94338447-cb9fc400-0024-11eb-8426-400c9ed00daa.jpg)
这是和老师的聊天记录

**Comment by UNIDY2002** [comment]
好的谢谢！

**Comment by SaltyKitkat** [comment]
![图片](https://user-images.githubusercontent.com/56984513/94339018-5aaedb00-0029-11eb-9336-a84cdc8bfa26.png)
![图片](https://user-images.githubusercontent.com/56984513/94339020-5edaf880-0029-11eb-9189-3a98a4507301.png)
这是老师那边给的反馈

**Comment by UNIDY2002** [comment]
嗯，明白了

**Comment by SaltyKitkat** [comment]
![photo_2020-09-26_18-53-07](https://user-images.githubusercontent.com/56984513/94339091-e32d7b80-0029-11eb-9e08-b36e6a1b66ee.jpg)
![photo_2020-09-26_18-53-22](https://user-images.githubusercontent.com/56984513/94339092-e4f73f00-0029-11eb-89e3-fef01c3b5c44.jpg)
这是老师那边的反馈

**Comment by UNIDY2002** [comment]
嗯嗯，明白了

**Comment by UNIDY2002** [comment]
最后，也非常感谢你帮我发现了这个问题！也代我感谢一下这位老师ww
