### ISSUE TITLE
Network failure

### ISSUE THREAD

**Issue by duskmoon314** [UNIDY2002/THUInfo#39]
从昨天下午到现在一直无法使用，报错是Network failure, please retry.

校园网、4G皆如此

**Comment by UNIDY2002** [comment]
谢谢反馈！

为了方便问题定位，可否进一步反馈一下：
成绩单、消费查询、新闻动态这三个部分是否都提示Network failure？如果不是，哪些部分可以正常使用？

**Comment by duskmoon314** [comment]
成绩单、消费查询都是Network failure，新闻动态一直在加载没有数据，4G的条件下。其他情况还未测试过。

**Comment by Ashitemaru** [comment]
ios的话可以先尝试一下清理后台之后重新登录

**Comment by Ashitemaru** [comment]
ios的话可以试着先注销或者关闭app（清后台）之后重新登录 如果有进一步的问题欢迎反馈

**Comment by duskmoon314** [comment]
注销后重新登录解决了

**Comment by UNIDY2002** [comment]
谢谢！不过这种情况对用户体验确实不太好，后续看看能不能改进一下。
