### ISSUE TITLE
一些反馈和建议

### ISSUE THREAD

**Issue by Markghz** [UNIDY2002/THUInfo#61]
感谢开发者的贡献！初步使用过程中发现了以下两个问题：
1. 查看教室资源的时候一直显示网络异常，4G和校园网Wi-Fi都这样，是什么原因呢？
2. 反馈输入框，没有设置按钮收起输入法键盘，很不方便，导致我没法按那个提交反馈的按钮🙈🙈

**Comment by UNIDY2002** [comment]
谢谢反馈！
1. 其它页面也存在一直显示网络异常的情况嘛？
2. 收到，这可能与设备相关，请问你的手机型号是？

**Comment by Markghz** [comment]
> 谢谢反馈！
> 
> 1. 其它页面也存在一直显示网络异常的情况嘛？
> 2. 收到，这可能与设备相关，请问你的手机型号是？

秒回啊😂

1. 成绩单也会出现这个情况（不过我是研究生，不确定是不是跟本科生不一样）
2. 我的型号是iPhone 6s，系统版本是iOS13.7

**Comment by UNIDY2002** [comment]
好的，再次感谢您的反馈！

**Comment by UNIDY2002** [comment]
已修复：
5143e7991664ad32911b4418f1c3d8f5dde3239c

**Comment by Markghz** [comment]
@UNIDY2002 想问一下，最近的版本都没有在AppStore上架吗？我进入app能看到更新提示，但是去AppStore好像没有新版本可以下载。

**Comment by UNIDY2002** [comment]
@Markghz 对，在审核，可能需要一两天……
@Ashitemaru umm你等审核过了再在APP内放更新通知吧hh

**Comment by Ashitemaru** [comment]
是有这个打算的 目前新版本还在审核队列中 等到有新版本出来我会发布相应通知
