### ISSUE TITLE
电费充值失败

### ISSUE THREAD

**Issue by Phillips233** [UNIDY2002/THUInfo#63]
电费充值后没有任何响应，总台处也没有收到，造成了经济损失

**Comment by UNIDY2002** [comment]
抱歉刚刚才看到，请尽快留下联系方式（GitHub不方便的话应用内反馈也可），我们会进行妥善处理。

**Comment by Phillips233** [comment]
电话：17809261212
邮箱：197617767@qq.com

**Comment by UNIDY2002** [comment]
OK，收到，为保护隐私我将你的这条评论先删掉了

**Comment by Phillips233** [comment]
好

**Comment by Phillips233** [comment]
充了两百多呢 😭😭

**Comment by UNIDY2002** [comment]
这个问题我们之前初步的判断是，学校的充值接口使用同学的用户名作为关键字，存在中文编码问题。我们前段时间发现学校修改了这个接口，改成了传入同学的学号。THUInfo 也进行了适配，见下一个版本。希望这个改动能够解决这个问题。
这个 issue 先关了。
