### ISSUE TITLE
关于成绩单的显示美化

### ISSUE THREAD

**Issue by Sim233** [UNIDY2002/THUInfo#82]
【非功能性问题，仅是界面优化建议】
成绩单界面在划动的时候会保持所在的学年学期置顶，这是好事；但是目前的实现（iPad端，版本2.1.1）里的这个置顶的内容（比如“2020-春”）会和下面的课程相重合，有点不好看。
建议“2020-春”置顶固定时，改成不透明的框，不要把下面盖住的字显示出来。

**Comment by UNIDY2002** [comment]
诶，居然会这样嘛，我们做的时候都不知道有这个feature😂😂（可能是iPad版特有……？）
不管怎样，确实可以看看把背景改成不透明的

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Sim233** [comment]
啊，刚才看了一下，我的安卓手机端，版本2.1.0上没有这个置顶固定……可能是iPad的特有功能？？不太清楚。

**Comment by UNIDY2002** [comment]
这么看来应该确实是平台相关。

不过按理也应该给平板设备做更好的适配来着的，适配平板设备的坑留给寒暑假填吧（

**Comment by UNIDY2002** [comment]
确实是平台相关，不过是我没仔细看[文档](https://reactnative.dev/docs/sectionlist#rendersectionheader)hhh
> # renderSectionHeader
> Rendered at the top of each section. These stick to the top of the ScrollView by default on iOS.

现在设置了不透明背景，谢谢反馈！
