### ISSUE TITLE
关于体测成绩

### ISSUE THREAD

**Issue by Sim233** [UNIDY2002/THUInfo#83]
在体测中心有体测各项分数折合为总分的标准，建议在体测成绩模块中增加一个“折合总分（仅供参考）”字段，应当不太麻烦。
（考虑到体测可能有各种特殊情况，故可以加上（仅供参考），以提示这个数值是计算得出的？）

**Comment by UNIDY2002** [comment]
谢谢反馈！我觉得这挺合理的，应该可以做

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
