### ISSUE TITLE
APP内的反馈难以提交

### ISSUE THREAD

**Issue by Sim233** [UNIDY2002/THUInfo#84]
iPad端，版本2.1.1
设置->反馈里输入后会打开输入键盘，但是输入后似乎不能把这个键盘收起来？而提交按钮在最下方，刚好被输入键盘挡住。
可以考虑把提交按钮放在界面上方？或者找个办法能把输入框收起来？

**Comment by UNIDY2002** [comment]
唔，我们的想法是，反馈的输入框不是有边框的嘛，点击输入框外部可以实现收起键盘，不知道这种方式在iPad上有没有问题

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Sim233** [comment]
草，我蠢了，对不起（
点击输入框外部是可以收起的（

**Comment by UNIDY2002** [comment]
没事没事，我们以后也在APP中加上相应的提示。
那这个issue先关了
