### ISSUE TITLE
卫生成绩界面黑屏

### ISSUE THREAD

**Issue by Sim233** [UNIDY2002/THUInfo#85]
点进去卫生成绩，界面黑屏，只有一行1/1，是什么情况？

**Comment by UNIDY2002** [comment]
从代码上看应该是获取到了卫生成绩图片的网址，但网址无效或因为网络原因没加载出来。
如果是网络原因的话可能是间歇性的，你可以过几天再看看。如果是获取到的网址无效的话……那应该确实是需要修一修的bug了

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
