### ISSUE TITLE
Added TUNA/BFSU mirror as release source

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [UNIDY2002/THUInfo#87]
Ref to tuna/tunasync-scripts/pull/102, any changes made in tuna/tunasync-scripts would be deployed **soon** in [tuna mirror](https://mirrors.tuna.tsinghua.edu.cn) and [bfsu mirror](https://mirrors.bfsu.edu.cn).

Hence changes in README could be made.

The mechanism is that tuna/bfsu mirrors sync from github-release periodically, hence no changes should be made here as the current release method is sufficient.

**Comment by UNIDY2002** [comment]
Wow, it's cool!
Great thanks!

**Comment by ZenithalHourlyRate** [comment]
Now it is on both
https://mirrors.tuna.tsinghua.edu.cn/github-release/UNIDY2002/THUInfo/
and
https://mirrors.bfsu.edu.cn/github-release/UNIDY2002/THUInfo/

You may add it in README.

**Comment by UNIDY2002** [comment]
Thanks!
