### ISSUE TITLE
希望可以不登录使用树洞

### ISSUE THREAD

**Issue by SainoNamkho** [UNIDY2002/THUInfo#90]

**Comment by UNIDY2002** [comment]
谢谢反馈，不过这可能并不太符合T大树洞那边的设计……？

传送门：[T大树洞](https://thuhole.com/)、[T大树洞社区规范](https://thuhole.com/policy.html)

**Comment by SainoNamkho** [comment]
> 谢谢反馈，不过这可能并不太符合T大树洞那边的设计……？
> 
> 传送门：[T大树洞](https://thuhole.com/)、[T大树洞社区规范](https://thuhole.com/policy.html)

问题不大吧

> 不得使用T大树洞网页版、T大树洞app版和THUInfo( https://github.com/THUInfo/THUInfo )以外的客户端、脚本等访问方式，未经T大树洞团队明确许可，访问T大树洞的相关服务、下载T大树洞服务提供的相关内容；违者造成恶劣影响的，T大树洞团队有权调查、封禁传播人账户，并追究法律责任。
反正都是用token。

**Comment by UNIDY2002** [comment]
唔，抱歉我之前理解可能出了偏差。

是挺合理的建议，这样也有助于消除用户对于树洞token和学校账号是否会串号的担心。

所以你的想法是在登录页面也放一个树洞入口嘛，还是有什么更好的想法

**Comment by SainoNamkho** [comment]
> 唔，抱歉我之前理解可能出了偏差。
> 
> 是挺合理的建议，这样也有助于消除用户对于树洞token和学校账号是否会串号的担心。
> 
> 所以你的想法是在登录页面也放一个树洞入口嘛，还是有什么更好的想法

是的，而且很多功能似乎都不需要学生账号，是否可以考虑直接进入程序界面，使用时按需登录呢？

**Comment by UNIDY2002** [comment]
不错的建议！
我们下一次大改的时候考虑重构一下。
谢谢！

**Comment by UNIDY2002** [comment]
树洞正在开发官方APP，未来THUInfo内树洞相关可能不再积极维护，故暂且关闭这个issue。
